In [16]:
import numpy as np
np.set_printoptions(suppress = True, linewidth=100, precision = 2)

In [2]:
np.sort(np.array([1, 3, 2, 4, 5]))

array([1, 2, 3, 4, 5])

In [6]:
np.sort(np.array([[1, 3, 2, 4, 5], [7, 8, 9, 10, 11]]))

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

In [8]:
data=np.genfromtxt('data/Real_estate(cleaned).csv', delimiter=';', skip_header=1)

In [49]:
temp_mean = np.nanmean(data, axis=0)
temp_mean

C:\Users\shopp\AppData\Local\Temp\ipykernel_30844\2189587286.py:1: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(data, axis=0)


array([      nan,       nan,       nan,       nan,       nan,    903.79,       nan,       nan,
             nan,       nan,       nan,       nan,       nan,       nan,       nan,       nan,
            3.6 ,       nan,       nan, 270777.63])

In [22]:
columns_strings = np.argwhere(np.isnan(temp_mean)).squeeze()
columns_strings

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 17, 18], dtype=int64)

In [25]:
columns_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze()
columns_numeric

array([ 5, 16, 19], dtype=int64)

In [26]:
data_numeric = np.genfromtxt('data/Real_estate(cleaned).csv',
                                delimiter=';',
                                skip_header=1,
                                usecols=columns_numeric,
                                filling_values=np.nanmax(data)+1)

In [27]:
matrix = np.array([[16,12], [34,45]])

In [28]:
np.histogram2d(matrix[0], matrix[1], bins=2)

(array([[0., 1.],
        [1., 0.]]),
 array([12., 14., 16.]),
 array([34. , 39.5, 45. ]))

In [31]:
matrix[1]

array([34, 45])

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6], [1, 1, 1]])

In [36]:
data_new = np.genfromtxt('data/Real_estate(cleaned).csv',
                            delimiter=';')

In [37]:
np.isnan(data_new).sum()

3425

In [40]:
header = np.genfromtxt('data/Real_estate(cleaned).csv',
                            delimiter=';',
                            skip_footer=data_new.shape[0] -1,
                            dtype='str')

In [41]:
header

array(['id', 'building', 'date_sale', 'type', 'property_number', 'area', 'status', 'customerid',
       'entity', 'name', 'surname', 'birth_date', 'gender', 'country', 'state', 'purpose',
       'deal_satisfaction', 'mortgage', 'source', 'price($)'], dtype='<U17')

In [42]:
array_a = np.array([[12,3,4],[9,10,-3],[8,19,25]])

In [44]:
np.ptp(array_a, axis=0)

array([ 4, 16, 28])

In [46]:
heights= np.array([
    [162,202,175,160],
    [200,185,193,180],
    [189,181,172,168],
    [183,195,199,167]
])

In [48]:
np.quantile(heights, 0.75)

193.5

In [50]:
temp_mean_new = np.nanmean(data_new, axis=0)

C:\Users\shopp\AppData\Local\Temp\ipykernel_30844\1120354216.py:1: RuntimeWarning: Mean of empty slice
  temp_mean_new = np.nanmean(data_new, axis=0)


In [52]:
a = np.argwhere(np.isnan(temp_mean_new)).squeeze()
a

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 17, 18], dtype=int64)

In [54]:
b= np.argwhere(np.isnan(temp_mean_new) == False).squeeze()

In [66]:
data_strings = np.genfromtxt("data/Real_estate(cleaned).csv", delimiter=";", skip_header=1, autostrip=True,
                                   usecols=a, dtype=np.str_)
data_strings.shape

(200, 17)

In [67]:
np.unique(data_strings[:,7])

array(['Company', 'Individual', 'nan'], dtype='<U11')

In [72]:
np.percentile(data_numeric[:, 2], 40)

229925.43

In [83]:
sum(((data_numeric[:, 0] >= 1023) & (data_numeric[:,0] <= 1329)))

34

In [84]:
data_strings[:,12]

array(['USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA',
       'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA',
       'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'UK', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA',
       'USA', 'USA', 'Belgium', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA',
       'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'Russia', 'USA', 'USA', 'USA', 'USA',
       'USA', 'Denmark', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'Germany', 'USA', 'USA', 'USA',
       'USA', 'Mexico', 'USA', 'USA', 'USA', 'USA', 'USA', 'UK', 'USA', 'USA', 'USA', 'USA', 'USA',
       'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA',
       'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA', 'USA',
       'Russia', 'USA', 'USA', 'USA', 'USA', 'USA', 'Belgium', 'USA', 'USA', 'USA', 'USA', 'USA',
       'USA', 'USA', 'USA