In [289]:
import numpy as np
np.set_printoptions(suppress = True, linewidth=100, precision = 2)

In [290]:
raw_data_np = np.genfromtxt("data/loan-data.csv", delimiter=";", skip_header=1, autostrip=True)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [291]:
np.isnan(raw_data_np).sum()

88005

In [292]:
temporary_fill = np.nanmax(raw_data_np) + 1
temporary_mean = np.nanmean(raw_data_np, axis=0)

C:\Users\shopp\AppData\Local\Temp\ipykernel_35812\2996838478.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np, axis=0)


In [293]:
# Which columns have only nans?
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [294]:
temporary_stats = np.array([np.nanmin(raw_data_np, axis=0),
                            temporary_mean,
                            np.nanmax(raw_data_np, axis=0)])

C:\Users\shopp\AppData\Local\Temp\ipykernel_35812\902197374.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np, axis=0),
C:\Users\shopp\AppData\Local\Temp\ipykernel_35812\902197374.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis=0)])


In [295]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

### Split dataset into columns holding integers and dataset full of strings

In [296]:
# A column that has nan as its value of the (nan!!)-mean is a column that has only nans/aka strings
# squeeze() to make array one-dimensional
columns_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [297]:
columns_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [298]:
loan_data_strings = np.genfromtxt("data/loan-data.csv", delimiter=";", skip_header=1, autostrip=True,
                                   usecols=columns_strings, dtype=np.str_)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [299]:
loan_data_numeric = np.genfromtxt("data/loan-data.csv", delimiter=";", skip_header=1, autostrip=True,
                                   usecols=columns_numeric, filling_values=temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [300]:
# Load header only. Use skip_footer to skip everything except the header
header_full = np.genfromtxt("data/loan-data.csv", delimiter=";", skip_footer=raw_data_np.shape[0], autostrip=True,
                                   dtype=np.str_)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [301]:
header_strings, header_numeric = header_full[columns_strings], header_full[columns_numeric]

### Checkpoint

In [302]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header=checkpoint_header, data=checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [303]:
checkpoint_test = checkpoint("data/loan-data-checkpoint", header_full, raw_data_np)

In [304]:
checkpoint_test["header"]

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

### Column issue date

In [305]:
np.unique(loan_data_strings[:, 0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [306]:
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:, 0], "-15")

In [307]:
np.unique(loan_data_strings[:, 0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [308]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep','Oct', 'Nov', 'Dec'])

In [309]:
for i in range(13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                      i,
                                      loan_data_strings[:,0])

In [310]:
np.unique(loan_data_strings[:, 0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [311]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [312]:
np.unique(loan_data_strings[:, 1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [313]:
# Goal: Split into two groups: "bad" and "good" loans. No data = "bad"
# Good = 1
# Bad = 0
status_bad = np.array(["", "Charged Off", "Default", "Late (31-120 days)"])

In [314]:
loan_data_strings[:, 1] = np.where(np.isin(loan_data_strings[:, 1], status_bad), 0, 1)

In [315]:
np.unique(loan_data_strings[:, 1])

array(['0', '1'], dtype='<U69')

### Term

In [316]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [317]:
np.unique(loan_data_strings[:, 2])

array(['', '36 months', '60 months'], dtype='<U69')

In [318]:
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:, 2], " months")
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [319]:
header_strings[2] = "term_months"

In [320]:
# Set missing values to worse case scenario
loan_data_strings[:, 2] = np.where(loan_data_strings[:, 2] == "",
                                      "60",
                                      loan_data_strings[:, 2])

In [321]:
np.unique(loan_data_strings[:, 2])

array(['36', '60'], dtype='<U69')

### Grade and Subgrade

In [322]:
np.unique(loan_data_strings[:, 3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [323]:
loan_data_strings[:,4]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [324]:
np.unique(loan_data_strings[:, 4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [325]:
# Fill out missing values in the subgrade column by using the grade column and assigning the worst subgrade of the respective class
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:, 4]  = np.where((loan_data_strings[:, 4] == "") & (loan_data_strings[:, 3] == i),
                                        i + "5",
                                        loan_data_strings[:, 4])

In [326]:
np.unique(loan_data_strings[:, 4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [327]:
np.unique(loan_data_strings[:, 4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [328]:
# Only 9 missing values left. Assign them to a subgrade worse than G5
loan_data_strings[:, 4]  = np.where(loan_data_strings[:, 4] == "",
                                    "H1",
                                    loan_data_strings[:, 4])

In [329]:
np.unique(loan_data_strings[:, 4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [330]:
# Information from grade and subgrade is redundant. Drop grade column
loan_data_strings = np.delete(loan_data_strings, 3, axis=1)

In [331]:
header_strings = np.delete(header_strings, 3)

In [332]:
keys = list(np.unique(loan_data_strings[:, 3]))
values = list(range(1, np.unique(loan_data_strings[:, 3]).shape[0] + 1))
dict_sub_grade = dict(zip(keys, values))

In [333]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [334]:
for i in np.unique(loan_data_strings[:, 3]):
    loan_data_strings[:, 3]  = np.where(loan_data_strings[:, 3] == i,
                                        dict_sub_grade[i],
                                        loan_data_strings[:, 3])

### Verification

In [335]:
np.unique(loan_data_strings[:, 4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [336]:
loan_data_strings[:, 4] = np.where((loan_data_strings[:, 4] == "Source Verified") | (loan_data_strings[:,4] == "Verified") , 1, 0)

In [337]:
np.unique(loan_data_strings[:, 4])

array(['0', '1'], dtype='<U69')

### URL

In [338]:
loan_data_strings[:, 5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [339]:
np.chararray.strip(loan_data_strings[:, 5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [340]:
loan_data_strings[:, 5] = np.chararray.strip(loan_data_strings[:, 5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [341]:
loan_data_strings[:, 5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [342]:
loan_data_numeric[:, 0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [343]:
np.array_equal(loan_data_strings[:, 5].astype(dtype=np.int32), loan_data_numeric[:, 0].astype(dtype=np.int32))

True

In [344]:
loan_data_strings = np.delete(loan_data_strings, 5, axis=1)
header_strings = np.delete(header_strings, 5)

In [345]:
header_strings

array(['issue_d', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

### State Address

In [346]:
header_strings[5] = "state_address"

In [347]:
np.unique(loan_data_strings[:, 5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [348]:
np.unique(loan_data_strings[:, 5]).size

50

In [349]:
np.unique(loan_data_strings[:, 5], return_counts=True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [350]:
# Sort states and info on how many loans are from each state
states_names, states_count = np.unique(loan_data_strings[:, 5], return_counts=True)
states_count_sorted = np.argsort(-states_count) # Indicies of states_count sorted in descending order
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [351]:
# Problem: Way too many entries for '', i.e. even more than for the most states.
# Since most states would have low number of applications, the '' category would be a massive outlier.
# Solution: Assigning states to different categories so that they are less prone to outliers.

# Step 1: Assign 0 to entries without state info
loan_data_strings[:,5] = np.where(loan_data_strings[:,5] == '',
                                  0,
                                  loan_data_strings[:,5])
# Step 2: Form geographical regions
states_west = np.array(["AK", "AZ", "CA", "CO", "HI", "ID", "MT", "NV", "NM", "OR", "UT", "WA", "WY"])
states_south = np.array(["AL", "AR", "DE", "FL", "GA", "KY", "LA", "MD", "MS", "NC", "OK", "SC", "TN", "TX", "VA"])
states_midwest = np.array(["IA", "IL", "IN", "KS", "MI", "MN", "MO", "ND", "NE", "OH", "SD", "WI"])
states_east = np.array(["CT", "DC", "MA", "ME", "NH", "NJ", "NY", "PA", "RI", "VT", "WV"])

In [352]:
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_west), 1, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_south), 2, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_midwest), 3, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_east), 4, loan_data_strings[:,5])

In [353]:
np.unique(loan_data_strings[:, 5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

### Converting to Numbers

In [354]:
loan_data_strings = loan_data_strings.astype(dtype=int)

### Checkpoint: Strings

In [355]:
header_strings

array(['issue_d', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [356]:
checkpoint_strings = checkpoint("data/Checkpoint-Strings", header_strings, loan_data_strings)

In [357]:
checkpoint_strings["header"]

array(['issue_d', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [358]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

## Numeric data

In [359]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [360]:
# How many missing values were filled with the temporary_fill value?
np.isin(loan_data_numeric, temporary_fill).sum()

8005

### ID

In [361]:
np.isin(loan_data_numeric[:,0], temporary_fill).sum()

0

In [362]:
temporary_stats[:, columns_numeric]
# min, mean, max

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

### Funded Amount

In [363]:
# Funded amount should be set to minimum value (to reflect worst case scenario)
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill,
                                  temporary_stats[0, columns_numeric[2]],
                                    loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

### Loan amount, interest rate, total payment, installment

In [364]:
# assign max values to loan amount, interest rate, total payment and installment
# the relevant columns are in 1, 3, 4 and 5
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill,
                                      temporary_stats[2, columns_numeric[i]],
                                      loan_data_numeric[:,i])

### Currency exchange

In [365]:
EUR_USD = np.genfromtxt("data/EUR-USD.csv", delimiter=",", skip_header=1, autostrip=True, usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [366]:
# Assign end of day exchange rate, using monthly information.
# where no monthly information is available, use the average yearly exchange rate

exchange_rate = loan_data_strings[:,0]

for i in range(1,13):
    exchange_rate = np.where(loan_data_strings[:,0] == i,
                             EUR_USD[i-1],
                             exchange_rate)

exchange_rate = np.where(exchange_rate == 0,
                            np.mean(EUR_USD),
                            exchange_rate)

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [367]:
print(exchange_rate.shape)
print(loan_data_numeric.shape)

(10000,)
(10000, 6)


In [368]:
# Match dimensions:
exchange_rate = np.reshape(exchange_rate, (exchange_rate.shape[0], 1))

In [369]:
# Add exchange rate to numeric data (as last column)
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))

In [370]:
loan_data_numeric.shape

(10000, 7)

In [371]:
header_numeric = np.concatenate((header_numeric, np.array(["exchange_rate"])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

### Convert currency

In [372]:
columns_dollar = np.array([1, 2, 4, 5])

In [373]:
loan_data_numeric[:, columns_dollar]

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,  1372.97,  2185.64],
       [35000.  , 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]])

In [374]:
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [375]:
# Add Euro values in extra columns
for i in columns_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:, i] / loan_data_numeric[:, 6], (loan_data_numeric.shape[0], 1))))

In [376]:
loan_data_numeric.shape

(10000, 11)

In [377]:
# Add headers to new columns
header_additional = np.array([column_name + "_EUR" for column_name in header_numeric[columns_dollar]])
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [378]:
header_numeric = np.concatenate((header_numeric, header_additional))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [379]:
header_numeric[columns_dollar] = np.array([column_name + "_USD" for column_name in header_numeric[columns_dollar]])
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [380]:
# Reoder columns so that USD and EUR values are next to each other
columns_index_order= [0, 1, 7, 2, 8, 3, 4, 9, 5, 10, 6]

In [381]:
header_numeric = header_numeric[columns_index_order]
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [382]:
loan_data_numeric = loan_data_numeric[:, columns_index_order]

### Interest Rate

In [383]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [384]:
# Change to percentage
loan_data_numeric[:,5] = loan_data_numeric[:,5] / 100
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint Numeric

In [385]:
checkpoint_numeric = checkpoint("data/Checkpoint-Numeric", header_numeric, loan_data_numeric)

In [386]:
checkpoint_numeric["header"], checkpoint_numeric["data"]

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## Putting everything together

In [387]:
print(checkpoint_strings["data"].shape)
print(checkpoint_numeric["data"].shape)

(10000, 6)
(10000, 11)


In [389]:
np.hstack((checkpoint_numeric["data"], checkpoint_strings["data"])).shape

(10000, 17)

In [390]:
loan_data = np.hstack((checkpoint_numeric["data"], checkpoint_strings["data"]))

In [391]:
np.isnan(loan_data).sum()

0

In [392]:
np.concatenate((checkpoint_numeric["header"], checkpoint_strings["header"]))

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_d', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [393]:
header_full = np.concatenate((checkpoint_numeric["header"], checkpoint_strings["header"]))

### Sort dataset

In [394]:
# Sort data by ID
np.sort(loan_data[:,0])

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.])

In [395]:
np.argsort(loan_data[:,0])

array([2086, 4812, 2353, ..., 4935, 9388, 8415], dtype=int64)

In [397]:
loan_data = loan_data[np.argsort(loan_data[:,0])]
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [399]:
# Double check that data is sorted by ID
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

### Storing the Dataset

In [401]:
loan_data = np.vstack((header_full, loan_data))

In [402]:
np.savetxt("data/loan-data-preprocessed.csv", loan_data, fmt="%s", delimiter=";")