## Chapter 4: Training Models
General overview of models and how to train them. Code based on the book, chapter IV "Training Models".

Modified and commented to experiment with code

In [27]:
import numpy as np
import pandas as pd

In [3]:
# Generate linear data
np.random.seed(42)
m = 100
X = 2 * np.random.rand(m, 1)
y = 4 + 3 * X + np.random.randn(m, 1)

## 4.1. Ways to solve the minimization problem

### 4.1.1. Normal equation

![MSE](MSE.png "MSE")  
MSE  
  
![Vectorized MSE](Vectorized.png "Vectorized MSE")  
Vectorized MSE  
  
![Derivative of MSE](Derivative.png "Derivative of MSE")  
Derivative  
  
![Find min](Minimize.png "Minimize Derivative")  
Minimize derivative  
  
![Solving](Solving.png "Solving derivative")  
Solving  
  
![Normal Equation](NormalEquation.png "Result: Normal Equation")  
Solution/Normal Equation  

In [4]:
from sklearn.preprocessing import add_dummy_feature

X_b = add_dummy_feature(X) # add x0 = 1 to each instance
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)
theta_best

array([[4.21509616],
       [2.77011339]])

In [5]:
# Or more ML-like implementation
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X, y)
lin_reg.intercept_, lin_reg.coef_

(array([4.21509616]), array([[2.77011339]]))

### 4.1.2. Gradient Descent

Gradient Descent is more flexible. Normal equation is computationally complex (O(n<sup>2.4</sup>) - O(n<sup>3</sup>)) and might not exist for all problems (i.e. non-linear relations)

![Find min](Minimize.png "Minimize Derivative")  

In [6]:
# Batch Gradient Descent
eta = 0.1 # learning rate
n_iterations = 1000

np.random.seed(42)
theta = np.random.randn(2,1) # randomly initialized model

for epoch in range(n_iterations):
    gradients = 2/len(X_b) * X_b.T.dot(X_b.dot(theta) - y)
    theta = theta - eta * gradients
    
theta

array([[4.21509616],
       [2.77011339]])

In [7]:
# Stochastic Gradient Descent
n_iterations = 50
t0, t1 = 5, 50 # learning schedule hyperparameters

# Define a learning schedule to decrease the learning rate over time
def learning_schedule(t):
    return t0 / (t + t1)

np.random.seed(42)
theta = np.random.randn(2,1) # randomly initialized model

for epoch in range(n_iterations):
    for i in range(len(X_b)):
        random_index = np.random.randint(len(X_b))
        xi = X_b[random_index:random_index+1] # pick a random instance
        yi = y[random_index:random_index+1]
        gradients = 2 * xi.T.dot(xi.dot(theta) - yi)
        eta = learning_schedule(epoch * len(X_b) + i)
        theta = theta - eta * gradients

theta

array([[4.21076011],
       [2.74856079]])

In [8]:
# More ML-like implementation
from sklearn.linear_model import SGDRegressor

sgd_reg = SGDRegressor(max_iter=1000,tol=1e-5, penalty=None, eta0=0.01,
                       n_iter_no_change=100, random_state=42)
# tol: tolerance for stopping criteria
# penalty: regularization term (None for no regularization)
# eta0: initial learning rate
# n_iter_no_change: number of iterations with no improvement before stopping

sgd_reg.fit(X, y.ravel()) # ravel() flattens y into a 1D array

sgd_reg.intercept_, sgd_reg.coef_

(array([4.21278812]), array([2.77270267]))

## 4.2. Polynomial Regression
Above deals only with simple linear regression. The principles for solving polynomial regression tasks stay the same

In [9]:
# Generate nonlinear data
np.random.seed(42)
m = 100
X = 6 * np.random.rand(m, 1) - 3 # random values between -3 and 3
y = 0.5 * X**2 + X + 2 + np.random.randn(m, 1) # quadratic function

In [10]:
from sklearn.preprocessing import PolynomialFeatures

poly_features = PolynomialFeatures(degree=2, include_bias=False)
# Transform training data to a 2nd degree polynomial adding second-degree polynomial (but no bias term (x^0))
X_poly = poly_features.fit_transform(X)
lin_reg = LinearRegression()
lin_reg.fit(X_poly, y)
lin_reg.intercept_, lin_reg.coef_

(array([1.78134581]), array([[0.93366893, 0.56456263]]))

## 4.3. Regularization

### 4.3.1. Ridge Regression / L2 Regularization
Addition of regularization term to MSE   
!["Regularization Term"](Rigeterm.png)  
  
This equals the square of the L2 Norm  
!["L2 Norm"](L2Norm.png)  
L2 Norm  

  
This leads to full MSE as  
!["MSE with L2 Regularization"](rigeregression.png)  
  
Or (easier/more famous) as:  
!["MSE with L2 Regularization"](rige2.png)  
  
  
Again, this could be solved in closed-form (via Cholesky matrix factorization) or Gradient Descent.

In [11]:
sgd_reg = SGDRegressor(penalty='l2', alpha=0.1 / m, tol=None,
                          max_iter=1000, eta0=0.01, random_state=42)
# penalty: Regularization term (l2 = Ridge, l1 = Lasso)
# Because l2 does not divide the regularization term by m, it has to be added

sgd_reg.fit(X_poly, y.ravel()) # ravel() flattens y into a 1D array
sgd_reg.intercept_, sgd_reg.coef_

(array([1.78211323]), array([0.93420757, 0.56518136]))

### 4.3.2. Lasso Regression / L1 Regularization

Lasso Regression adds the L1 Norm to the MSE (but not squared like Ridge Regression)  
!["L1 Norm"](L1Norm.png)  
  
This leads to  
!["Lasso MSE"](Lasso.png)  
  
Note:
* Regularization term is often multiplied by 2 (because of derivative of MSE that leads to leading 2)
* Division by m/size of dataset often done.
* Combination of both also possible.

However, there is no fixed rule

In [12]:
# Code just as above, only with penalty='l1' for Lasso regression

### 4.3.3. Elastic Net Regression
Combination of Ridge Regression and Lasso Regression  
![Elastic Net Regression](ElasticNet.png)

In [14]:
from sklearn.linear_model import ElasticNet

elastic_net = ElasticNet(alpha=0.1, l1_ratio=0.5, random_state=42)
# l1_ratio: ratio of l1 and l2 regularization terms
elastic_net.fit(X, y)

(array([3.55886814]), array([0.81485127]))

### 4.3.4. Comparison

Ridge Regression:
* Good default
* When expected that (almost) all features relevant or cross-correlation between features

--> Stabilizes model by reducing weight of coefficients, but will not set them to zero  
  
Lasso Regression:
* When expected that only few features are relevant

--> Can set weights of coefficients to zero  
  
Elastic Net:
* Especially useful when more features than observations or when features correlated
* Preferred over Lasso because Lasso might be erratic in cases above

## 4.4. Example: Logistic regression
Logistic regression for classification on the iris dataset

### 4.4.1. Binary classification case
For binary classification, the sigmoid function will be used:  
![Sigmoid](sigmoid.png)  
  
Cost function in binary classification:  
![LogLoss](logloss.png)

In [24]:
from sklearn.datasets import load_iris

iris = load_iris(as_frame=True) # as_frame=True returns a pandas DataFrame
list(iris.keys())

['data',
 'target',
 'frame',
 'target_names',
 'DESCR',
 'feature_names',
 'filename',
 'data_module']

In [31]:
iris["data"].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [35]:
iris["target_names"]

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [36]:
iris["target"].head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int32

In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Do not use full dataset, but only pedal width
# Not using depreciated .values (like in the book)

iris_data = iris["data"]
iris_target = iris["target"]
target_names = iris["target_names"]


X = pd.DataFrame(iris_data["petal width (cm)"])

y = target_names[iris_target] == "virginica" # True for virginica, False for others

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [61]:
log_reg = LogisticRegression(random_state=42)
log_reg.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [67]:
intercept = log_reg.intercept_[0]
coef = log_reg.coef_[0][0]

# Only one feature, so decision boundary is a single point
decision_boundary = -intercept / coef
decision_boundary

1.6507579634643263

### 4.4.2. Multiclass classification case
For multiclass, softmax regression will be used  
![Softmax](softmax.png)  

And Cross-Entropy as cost function:  
![Cross-Entropy](crossentropy.png)  

In [72]:
X = pd.DataFrame(iris_data[["petal length (cm)", "petal width (cm)"]])
y = iris["target"]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [73]:
softmax_reg = LogisticRegression(C=30, random_state=42) 
# C is inverse of regularization strength (smaller = stronger) of the L2 regularization
softmax_reg.fit(X_train, y_train)

LogisticRegression(C=30, random_state=42)

In [77]:
new_data = pd.DataFrame([[5, 2]], columns=["petal length (cm)", "petal width (cm)"])
# Prediction for # petals = 5 cm lon and 2 cm wide.
# Added columns to make it a DataFrame and avoid Warning that prediction does not have a valid feature name

softmax_reg.predict(new_data)

array([2])

In [82]:
softmax_reg.predict_proba(new_data).round(2) # probabilities for each class

array([[0.  , 0.04, 0.96]])